version: '3.8'

services:
  forex-alert-engine:
    build: .
    container_name: forex_alert_engine
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./alerts.db:/app/alerts.db
    env_file:
      - .env
