services:
  - type: web
    name: najmul-fx
    env: python
    buildCommand: pip install --upgrade pip && pip install --prefer-binary -r requirements.txt
    startCommand: bash start.sh
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
      - key: DEFAULT_FEED_SOURCE
        value: simulation
